version: '2.4'

services:
  crawler_getlink:
    container_name: crawler_getlink 
    environment:
      KAFKA_HOSTS_DEFAULT: "kafka-server:9092"
      REDIS_HOST_DEFAULT: "crawler-redis"
      REDIS_PORT_DEFAULT: "6379"
      PG_HOST_DEFAULT: "crawler-postgres"
      PG_PORT_DEFAULT: "5432"
      PG_USER_DEFAULT: hoang
      PG_PASSWORD_DEFAULT: "4983"
      DATABASE_ENGINE_DEFAULT: "postgresql"
      CRAWL_TYPE_DEFAULT: candidate

    build:
      context: .
      dockerfile: docker/DockerfileGetlink
    networks: 
      - crawler-net
    restart: always
    scale: 2

  crawler_scraper:
    container_name: crawler_scraper
    environment:
      KAFKA_HOSTS_DEFAULT: "kafka-server:9092"
      REDIS_HOST_DEFAULT: "crawler-redis"
      REDIS_PORT_DEFAULT: "6379"
      PG_HOST_DEFAULT: "crawler-postgres"
      PG_PORT_DEFAULT: "5432"
      PG_USER_DEFAULT: hoang
      PG_PASSWORD_DEFAULT: "4983"
      DATABASE_ENGINE_DEFAULT: "postgresql"
      CRAWL_TYPE_DEFAULT: candidate

    build:
      context: .
      dockerfile: docker/DockerfileScraper
    networks: 
      - crawler-net
    restart: always
    scale: 6

  crawler-postgres:
    container_name: crawler-postgres
    image: postgres
    environment:
      POSTGRES_USER: hoang
      POSTGRES_PASSWORD: 4983
    ports:
      - "5432:5432"
    networks: 
      - crawler-net

  crawler-redis:
    container_name: crawler-redis
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - crawler-net

  zookeeper-server:
    container_name: zookeeper-server
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks: 
      - crawler-net

  kafka-server:
    container_name: kafka-server
    image: bitnami/kafka:latest
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    networks: 
      - crawler-net

networks:
  crawler-net:
    name: crawler-net
    driver: bridge
