version: '3'
services:
  getlink:
    build: .
      context: .
      dockerfile: Dockerfile_getlink
    restart: always
  scraper:
    build: .
      context: .
      dockerfile: Dockerfile_scraper
    restart: always