version: '2.4'
services:
  hoang_job_getlink:
    build:
      context: .
      dockerfile: docker/DockerfileGetlink
    restart: always
    scale: 2
  hoang_job_scraper:
    build:
      context: .
      dockerfile: docker/DockerfileScraper
    restart: always
    scale: 6