version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - crawl-net-01
    volumes:
      - crawl-data:/zookeeper

  kafka:
    build: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.123
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - crawl-data:/kafka
    networks:
      - crawl-net-01

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server"]
    hostname: redis
    networks:
      - crawl-net-01
    volumes:
      - crawl-data:/redis

  visitor:
    build: selenium
    command: ["python3", "getlinks.sh"]
    networks:
      - crawl-net-01
    volumes:
      - crawl-data:/visitor
  scraper:
    build: selenium
    command: ["python3", "extract.sh"]
    networks:
      - crawl-net-01
    volumes:
      - crawl-data:/scraper

networks:
  crawl-net-01:

volumes:
  crawl-data:
