version: '2.4'
services:
  hoang_job_getlink:
    build:
      context: .
      dockerfile: Dockerfile_getlink
    restart: always
    scale: 2
  hoang_job_scraper:
    build:
      context: .
      dockerfile: Dockerfile_scraper
    restart: always
    scale: 6