version: '2.4'

services:
  crawler_getlink:
    build:
      context: .
      dockerfile: docker/DockerfileGetlink
    restart: always
    scale: 2

  crawler_scraper:
    build:
      context: .
      dockerfile: docker/DockerfileScraper
    restart: always
    scale: 5

